### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [shafeequeq/SimpleToDoApp_Revised#1]
Hello Shafeeque, 

Looks great, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

Great to see you were able to complete a large number of extensions to your app already. Your project looks great. As you can probably tell, the extension tasks available on each project are the valuable learnings since they dive deeper into common real-world Android use cases. 

Be sure to take a look through our [organizing your source files guide](http://guides.codepath.com/android/Organizing-your-Source-Files#android-folder-structure) for tips on organizing your code as well.

Now that you've completed the pre-work, we'll be following up with you again shortly to outline the next steps in the admissions process.

**Comment by shafeequeq** [comment]
Thanks for the prompt response. Most of my organization is as per the standards given. Except for the interfaces which went inside the functionality e.g. alongwith adapters etc. 

Will try to move the interfaces and do some code cleanup 
Will keep refining the code and update the readme as I learn new concepts. and apply them to this project.

**Comment by shafeequeq** [comment]
Following additional changes were done after submission -
1) Cleanup DialogFragment UI to leverage style tips from Codepath documentation.
2) Leverage TextHint and TextError for Todo Item title textview.
3) Used CircleImageView library in the Recycler Items.
4) Used CalendarPicker and TimePicker libraries for editing Due-Date and time.
5) Code organization - moved all interfaces under a different package structure. All other structure was as per the recommended standards.
